---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Выбранный язык должен отображаться
  - Должна быть возможность выбрать другое изображение в карточке товара
  - Должен меняться язык в описании товара при смене языка
  - Должна быть кнопка показать все товары или вернуться на главную при выборе категорий
  - Должно быть всплывающее окно или сообщение при добавлении товара в корзину.
  - Должна быть возможность создания своего профиля и ЛК.
  - Должна быть возможность изменять количество товара в корзине
  - Можно сделать отображение мини-изображения товара в корзине
  - Должна быть кнопка возврата из корзины